# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.black_price <- function(forward, strike, sigma, tenor, callput) {
    .Call(`_letsberational_black_price`, forward, strike, sigma, tenor, callput)
}

.bachelier_price <- function(forward, strike, sigma, tenor, callput) {
    .Call(`_letsberational_bachelier_price`, forward, strike, sigma, tenor, callput)
}

.black_volatility <- function(price, forward, strike, tenor, callput) {
    .Call(`_letsberational_black_volatility`, price, forward, strike, tenor, callput)
}

.bachelier_volatility <- function(price, forward, strike, tenor, callput) {
    .Call(`_letsberational_bachelier_volatility`, price, forward, strike, tenor, callput)
}

